[project]
name = "learn-spark-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars>=1.16.0",
    "pyspark==3.5.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.0",
]
